Fixed wrong status code evaluation
- autorelease was signalign a project failed to release even if it
actually did it.
- Added a README file to the patches directory to explain the gist of
it.

Signed-off-by: Giovanni Meo <gmeo@cisco.com>

diff --git a/autorelease b/autorelease
--- a/autorelease
+++ b/autorelease
@@ -117,7 +117,11 @@ for repouri in $repositoryList; do
     # Commit the change done by use-latest-versions
     git commit -a -s -m "Updated to newer local release versions" && echo "Updated artifacts"
     
-    ${autoreleasebasedir}/localrelease --localm2repo "${localm2repo}" --settingsfile "${settingsfile}" --stagingrepodir "${stagingreleases}" --localrepodir "${localdeployrepo}" --logsdir "${locallogsdir}" --profiles "${mavenprofiles}" && echo "Release failed for ${repo}" || exit 1
+    ${autoreleasebasedir}/localrelease --localm2repo "${localm2repo}" --settingsfile "${settingsfile}" --stagingrepodir "${stagingreleases}" --localrepodir "${localdeployrepo}" --logsdir "${locallogsdir}" --profiles "${mavenprofiles}"
+    if [ ! $? == 0 ]; then
+        echo "Release failed for $repo"
+        exit 1
+    fi
     
     # Now stage the released artifacts
     mvn -Dwagon.source="file://${localdeployrepo}" -Dwagon.target="file://${stagingreleases}" wagon:merge-maven-repos -l "${locallogsdir}/merge-maven-repos.log"
